=== Borgaonkarchinmay/WTL_Assignments/employeeData.dtd
<!DOCTYPE employeeData 
[
<!ELEMENT employeeData (employee)>
<!ELEMENT employee (name, department, designation, education, salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT education (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
]>

=== Borgaonkarchinmay/WTL_Assignments/emloyeeData.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type = "text/xsl" href = "employeeData.xsl"?>
<!DOCTYPE note SYSTEM "employeeData.dtd">
<employeeData>


    <employee empId = "321">
        <name>Mark</name>
        <department>Human Resources</department>
        <designation>Junior</designation>
        <education>Master Arts</education>
        <salary>20000</salary>
    </employee>
    
    <employee empId = "322">
        <name>Brian</name>
        <department>Sales</department>
        <designation>Regional Manager</designation>
        <education>Bachlore Commerce</education>
        <salary>35000</salary>
    </employee>
    
    <employee empId = "323">
        <name>Alan</name>
        <department>Legal</department>
        <designation>Consultant</designation>
        <education>L.L.B</education>
        <salary>100000</salary>
    </employee>
    
    <employee empId = "324">
        <name>Tony</name>
        <department>Accounting</department>
        <designation>Manager</designation>
        <education>Master. Commerce</education>
        <salary>75000</salary>
    </employee>
    
    <employee empId = "325">
        <name>Yash</name>
        <department>Support</department>
        <designation>Senior Professional</designation>
        <education>Engineer</education>
        <salary>22000</salary>
    </employee>
    
    <employee empId = "326">
        <name>Atharv</name>
        <department>Business Development</department>
        <designation>Business Head</designation>
        <education>MBA</education>
        <salary>120000</salary>
    </employee>
    
    <employee empId = "327">
        <name>John</name>
        <department>Technical</department>
        <designation>SDE 3</designation>
        <education>Engineer</education>
        <salary>240000</salary>
    </employee>


</employeeData>
